### ISSUE TITLE
package version

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [sean-rohan-NOAA/akfishcondition#14]
@sean-rohan-NOAA I'm updating the sablefish condition indicator for the ESP. Are there method changes or error fixes I should know about in the new version of this package? This is the only condition indicator that uses the longline survey... Thanks.

**Comment by sean-rohan-NOAA** [comment]
@JaneSullivan-NOAA No changes that should affect how you're using the package. We've been updating the package but all of the changes are geared towards adding functions for GAP to produce the condition indicator and include GAP's condition indicators as data in the package.  The core functions used to calculate the indicator will not change this year.

If you install the current version of the package on the repo, you can see how we're planning to include indicators and metadata. 

Example:
akfishcondition:::EBS_INDICATOR

**Comment by JaneSullivan-NOAA** [comment]
Perfect. Thanks Sean.
